- components/TextEditOverlay.tsx
- screens/Profile/ProfileScreen.tsx
> updated overlay

- machines/vidItem.ts
- screens/Home/MyVids/AddVidModalMachine.ts
Update API request URLs to remove hard-coded prefix. 
Related backend PR: https://github.com/idpass/mimoto/pull/8
> Remove endpoint prefix

- README.md
- android/app/build.gradle
> Dev workflow APK build support env var for signing keystore.

- machines/vid.ts
- machines/vidItem.ts
- screens/Scan/ScanScreenController.ts
- screens/Scan/SendVidModalController.ts
> Filter shareable VIDs

- components/VidDetails.tsx
- machines/settings.ts
- machines/vidItem.ts
- screens/Home/OnboardingOverlay.tsx
- screens/Profile/ProfileScreen.tsx
- types/vid.ts
> Fix missing display data

- screens/Home/HomeScreenController.ts
> Fix crash when sharing VC

- components/QrScanner.tsx
- machines/app.ts
- machines/scan.ts
- screens/Scan/ScanScreen.tsx
- screens/Scan/ScanScreenController.ts
> App should ask for permission to location access when opening Scan QR page - added allow access button

- components/EditableListItem.tsx
> "Cancel" button doesn't behave correctly on "Edit name"

- components/QrScanner.tsx
> Fix missing allow camera button

- machines/request.ts
- package-lock.json
- screens/Request/RequestScreen.tsx
- screens/Request/RequestScreenController.ts
- screens/Scan/SelectVidOverlay.tsx
> Replace static VC labels

- components/MessageOverlay.tsx
- machines/scan.ts
- screens/Home/MyVids/AddVidModal.tsx
- screens/Home/MyVids/AddVidModalMachine.ts
- screens/Home/MyVidsTab.tsx
- screens/Scan/ScanScreen.tsx
- screens/Scan/SendVidModal.tsx
> Add abort button to all progress dialogs

- machines/scan.ts
- package-lock.json
- package.json
- screens/Scan/ScanScreen.tsx
- screens/Scan/ScanScreenController.ts
> Camera is not launched when device is in flight mode

- components/MessageOverlay.tsx
- machines/scan.ts
- screens/Home/MyVids/AddVidModal.tsx
- screens/Home/MyVids/AddVidModalMachine.ts
- screens/Home/MyVidsTab.tsx
- screens/Scan/ScanScreen.tsx
- screens/Scan/SendVidModal.tsx
> Revert "Add abort button to all progress dialogs"

- .github/workflows/android-custom-build.yml
This is a quick fix to have @paolo's build success
> Updated custom build yaml to decrypt google-services.json.gpg

- screens/Home/MyVids/AddVidModal.tsx
- screens/Home/MyVids/AddVidModalController.ts
- screens/Home/MyVids/AddVidModalMachine.ts
- screens/Home/MyVidsTab.tsx
- screens/Home/MyVidsTabController.ts
- screens/Home/MyVidsTabMachine.ts
> Download of VC is started when clicking "Back home" rather than when entering verification code

- package-lock.json
- package.json
Fixes crash when using the camera:
https://console.firebase.google.com/project/mosip-resident-app/crashlytics/app/android:io.mosip.residentapp/issues/3602ae7fa24165166d81e7fc4b3a2b84?time=last-hour&sessionEventKey=623B3684026200013DA2131FD34CE324_1656757464148946666
> fix: crash when using QR scanner

- components/VidDetails.tsx
> Header on ID downloaded through VID should say "VID"

- screens/Request/RequestScreen.tsx
> Text corrections

- screens/Request/RequestScreen.tsx
> "Show this QR code to request a VC" displayed when sharing VC is already in process

- screens/Home/HomeScreenController.ts
> User should land on "Received VIDs" screen after receiving VID

- components/VidDetails.tsx
> fix: missing data in VC details

- screens/Home/MyVcs/AddVcModalMachine.ts
- screens/Home/MyVcs/AddVcModalMachine.typegen.ts
Fixes #164 
---
**Note to reviewers**: the fix to the issue is [lines 126-129](https://github.com/idpass/inji/compare/develop...idpass:fix/164-cannot-change-id-type?expand=1#diff-07abe5e03fe99f78969216dc553ded9b0460cde88cbf71ccac7db93080b91af3R126-R129). The rest of the changes are from the XState VSCode extension cleaning up the state machine.
> fix: allow re-selecting ID in invalid state

- screens/Home/ViewVcModalController.ts
> Issue when unlocking/locking a VC - stuck on enter passcode screen

- screens/Home/ViewVcModal.tsx
> Remove Lock/Unlock options in VC

- README.md
- android/app/build.gradle
- android/app/src/main/res/values/strings.xml
- package.json
> Add MOSIP build profile

- screens/Home/OnboardingOverlay.tsx
> Onboarding Screen should be Scrollable

- screens/Home/OnboardingOverlay.tsx
added suggestion by QA for #175
> made scroll visible on onboarding scrollable views

- components/VcDetails.tsx
- components/ui/Button.tsx
- locales/en.json
- locales/fil.json
- machines/scan.ts
- screens/Request/RequestScreen.strings.json
- screens/Request/RequestScreen.tsx
- screens/Request/RequestScreenController.ts
- screens/Scan/ScanScreen.strings.json
- screens/Scan/ScanScreenController.ts
- screens/Scan/SendVcModalController.ts
Fixes more missing translations in #176
> fix: missing translations

- machines/app.ts
- machines/app.typegen.ts
- screens/Profile/ProfileScreen.tsx
- screens/Profile/ProfileScreenController.ts
> Add backend info to the settings page

- screens/AuthScreen.tsx
- screens/AuthScreenController.ts
> "Use biometrics" button should be disabled when device does not support feature. 

- screens/Scan/SendVcModal.tsx
Closes https://github.com/idpass/inji/issues/207
> removed placeholder checker

- components/ui/Layout.tsx
- components/ui/Modal.tsx
- screens/Request/RequestLayout.tsx
> Fix UI issues

- components/ui/Button.tsx
- locales/en.json
- machines/request.ts
- machines/request.typegen.ts
- screens/Request/RequestScreen.strings.json
- screens/Request/RequestScreen.tsx
- screens/Request/RequestScreenController.ts
> Fix Bluetooth toggle in iOS

- components/MessageOverlay.tsx
- components/ui/Button.tsx
- locales/en.json
- machines/request.ts
- machines/request.typegen.ts
- machines/scan.ts
- machines/scan.typegen.ts
- machines/vcItem.ts
- screens/Home/MyVcs/AddVcModal.tsx
- screens/Home/ViewVcModal.tsx
- screens/Request/RequestScreen.strings.json
- screens/Request/RequestScreen.tsx
- screens/Request/RequestScreenController.ts
- screens/Scan/ScanScreen.strings.json
- screens/Scan/ScanScreen.tsx
- screens/Scan/ScanScreenController.ts
- screens/Scan/SendVcModal.strings.json
- screens/Scan/SendVcModal.tsx
- screens/Scan/SendVcModalController.ts
Added a timeout when sharing a VC so the user can exit out and retry.
---
Fixes #230 
Related ticket that could be improved by these changes: mosip#109
> fix: stuck connecting

- machines/request.ts
- screens/Request/RequestScreen.tsx
- screens/Request/RequestScreenController.ts
> fix: bluetooth errors

- .gitignore
- components/DropdownIcon.tsx
- components/OIDcAuth.tsx
- ios/Podfile.lock
- locales/en.json
- machines/revoke.ts
- machines/revoke.typegen.ts
- machines/store.ts
- machines/store.typegen.ts
- machines/vc.ts
- machines/vcItem.ts
- machines/vcItem.typegen.ts
- screens/Home/HomeScreen.tsx
- screens/Home/HomeScreenController.ts
- screens/Home/ViewVcModal.strings.json
- screens/Home/ViewVcModal.tsx
- screens/Home/ViewVcModalController.ts
- screens/Profile/RevokeController.tsx
Address comment: https://github.com/idpass/inji/issues/210#issuecomment-1256052295
> Revoke VID

- components/Message.tsx
- ios/Podfile.lock
- screens/Request/RequestLayout.tsx
Closes [#120 ](https://github.com/mosip/inji/issues/120)
> Interrupted connection popup was not displayed after clicking reject on device B (iOS -> iOS)

- locales/fil.json
Closes [#122](https://github.com/mosip/inji/issues/122)
> Incoming Card's accept and request button is not translated to Filipino

- machines/revoke.ts
- machines/revoke.typegen.ts
- screens/Profile/RevokeController.tsx
https://github.com/mosip/inji/issues/144
> Using 'Bulk revoke VID' when there's is only one VID in My IDs does not revoke the VID.

- machines/revoke.ts
- machines/revoke.typegen.ts
bulk revoke should not proceed if there's a failure in request
> Bulk Revoke error handling

- machines/request.ts
- machines/scan.ts
- machines/scan.typegen.ts
- screens/Scan/ScanLayoutController.ts
- screens/Scan/SendVcScreen.tsx
- screens/Scan/SendVcScreenController.ts
- shared/smartshare.ts
> fix: disconnect popup missing when sharing is cancelled

- components/ui/Button.tsx
- ios/Podfile.lock
[#12](https://github.com/idpass/inji/issues/230#issuecomment-1260420870)
> adjusted minHeight if text is longer than one line in ios

- android/build.gradle
- android/gradle.properties
- ios/Podfile.lock
https://stackoverflow.com/questions/74258160/is-jcenter-down
> build: fix jcenter issues

- components/DropdownIcon.tsx
- components/VcDetails.tsx
- components/VcItem.tsx
- components/ui/themes/DefaultTheme.ts
- i18n.ts
- ios/Podfile.lock
- locales/en.json
- screens/Profile/ProfileScreen.strings.json
- screens/Profile/ProfileScreen.tsx
https://github.com/mosip/inji/issues/203
> RTL is not handled in inji app

- components/VcDetails.strings.json
- locales/en.json
- locales/fil.json
- screens/Home/ViewVcModal.tsx
- screens/Scan/SendVcScreen.tsx
https://github.com/mosip/inji/issues/223
> In inji app still labels and button remained in english even after language switch

- components/ui/Button.tsx
- ios/Podfile.lock
- locales/fil.json
https://github.com/mosip/inji/issues/223#issuecomment-1338717230
https://github.com/mosip/inji/issues/201#issuecomment-1338717370
> Filipino translation and button fix on ios

- components/ui/TextItem.tsx
https://github.com/mosip/inji/issues/197
> RTL is not handled in inji app - history screen

- android/build.gradle
- locales/en.json
- locales/fil.json
- machines/biometrics.ts
- machines/request.ts
- machines/request.typegen.ts
- machines/scan.ts
- machines/scan.typegen.ts
- machines/vc.typegen.ts
- screens/Request/RequestScreen.strings.json
- screens/Scan/ScanLayout.tsx
- screens/Scan/ScanLayoutController.ts
- screens/Scan/ScanScreen.strings.json
- screens/Scan/SendVcScreen.strings.json
- shared/smartshare.ts
Resolves:
- mosip#384
- mosip#394
- mosip#350
- mosip#249
- mosip#250
- mosip#252
> Fix biometrics and cancel flow
